{% set name = "googlemaps" %}
{% set version = "4.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googlemaps/google-maps-services-python/archive/refs/tags/v4.10.0.tar.gz
  sha256: cc07f739731ba4e0a4586543ad14470695addff8f30840748b9c3b89e393aa36
  patches:
    - 0001-remove-superfluous-build-requirement.patch

build:
  skip: True  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0


requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - requests >=2.20.0,<3.0

test:
  imports:
    - googlemaps
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - responses
  source_files:
    - tests

about:
  home: https://github.com/googlemaps/google-maps-services-python
  summary: Python client library for Google Maps Platform
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE  
  description: |
    Use Python? Want to geocode something? Looking for directions? Maybe matrices of directions? This library brings the Google Maps API Web Services to your Python application. Analytics
  doc_url: https://googlemaps.github.io/google-maps-services-python/docs/index.html
  dev_url: https://github.com/googlemaps/google-maps-services-python

extra:
  recipe-maintainers:
    - david-gang
    - giswqs
