travis:
  secure:
    BINSTAR_TOKEN: XeY83JBKUwvAzW0lLmU4Ve22K7AN5x4IAD4gNMnVdMwzIxEh64pN+h8z6WpfKMaR+JGfQOj0W9a8ghf06vrwFQe6CsZzrMbNXK1Xb+HNm9tBTYMksDAVPK9sN5qP4JMj6ADSvKBYqO8VpC8s9DmVCTGSRP9fPSw2xQy4TbU50EoeBPNMr+T+91E+og5CG/CoVSUafBawyCefSa3mpUwvt+Nu80HlMrNFluv97CoM2Hmqabotf6OutJyRgmeJ0s01MytC9qMUSlTqYQxboAllqqGe+SLxMAg5zdFx3ebunrNaeAKIIh3wgGN2ExWv+PcO+id6AoVf/fjFxeiH1OGvhMn72yI/xryh3ddw/uKpQ+S55CnxEgm452Vn5HJmk7Jb64ZxtMsmHd1PMh2ys3E3gwP8kxrt+nXo29Ook046DegF4s8mCLCkXsCJvYuGE7692dBc+T91WNiIk2a8HP4D1BEFOxcllzZlhEVbmEGPXmF6fYsA+y6GLCcNeB06N5D3ctqzqFr2+r9d8Qp7zVCBNBUfm9kShaGKgb6+h+M6DARYGscM9DBAqeOaoxQufzM4CpJaHXzxQpbJH7SLwdFIompWwLdisBT2IjwQxyIlgUz1D+3bpo2y46GSs1ioY10plrDiXZTGBTieVDQTrzYOzSk/I3bXtWilofxnStk9Hsk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
