travis:
  secure:
    BINSTAR_TOKEN: rsVMS7AJDT6imHLqEdsI9rWghuST7P6zofZdF4MhyFqet0kUv83O5rlzqwBuPNmniMwCHx8MFjMfcztHtvpE+pCPOm2Ec+8PAbfJ48KpreP/BOqPY1PyGUHAP8hY9yg7jtBBxCL1oW9skSd6G46SiJtHiahbKPgmqV84JbVTOfeZ/Ga6nJPOD3cOCzelehDdRcqWTYqqbf0PrEfqXfH3Uv/QvlIPMyhN0KkUPKe7K4alEUfdVYAvCyS1+vp91iyewRn6yg5N00DXp/qfHgwYkuxylD7gOYLycy9G7LANz/HAfBRC1OFKOyKDQwoP0XEwHm1RHFTp1qTp2fmcSgLZFG0rKEwgYjKKiQ+EbyxjxNHthrTMCbXDUdsENNJ10Yd14K91tAQ9s6uUk72ltVLmooHT5AgrPSV228Yhuvb9VtMPE191yryrbK4OXncNmjPeSGxRDx1UcgZNrFDOVe6X3D9tmWU+5hsLDothLh5EzWo2BVTpKmZsPVwZ5uHa92rSXwm6zVlobdd8Ntx7RcUyren9uFuiLrYL4pOyzT16yYhRizWFJVJ02Oeyn7H8okJeFaqGQrZzY1q+gJRCfqpATQiPbrmM/AXJG6Gp2zAmWHXvYeRCCp0GZYUHaW8OMBQdJuoSqzE2j1SXcrcERUNM1TFiTCfUwps3IDSfTl1sFAE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
